{% set name = "hdijupyterutils" %}
{% set version = "0.20.0" %}
{% set hash_type = "sha256" %}
{% set hash_val = "8785d4d89bced6b49347957af67c46814b096cb3d2d6f8effaf95a8e3f485d8c" %}

package:
    name: {{ name }}
    version: {{ version }}

source:
    fn: {{ name }}-{{ version }}.tar.gz
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    {{ hash_type }}: {{ hash_val }}

build:
    number: 0
    # The downstream sparkmagic dropped support for Python 3.6,
    # see https://github.com/jupyter-incubator/sparkmagic/blob/0.20.0/CHANGELOG.md#updates
    skip: True  # [py<37]
    script: {{ PYTHON }} -m pip install --no-deps --ignore-installed . -vv

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - ipykernel >=4.2.2
    - ipython >=5
    - ipywidgets >5.0.0
    - jupyter >=1
    - mock
    - nose
    - notebook >=4.2
    - numpy
    - pandas >=0.17.1

test:
  imports:
    - hdijupyterutils
  requires:
    - pip
  commands:
    - pip check || true

about:
  home: https://github.com/jupyter-incubator/sparkmagic/tree/master/hdijupyterutils
  license: BSD-3-Clause
  license_family: BSD
  license_url: https://github.com/jupyter-incubator/sparkmagic/blob/master/hdijupyterutils/LICENSE.md
  summary: Project with useful classes/methods for all projects created by the HDInsight team at Microsoft around Jupyter
  dev_url: https://github.com/jupyter-incubator/sparkmagic/tree/master/hdijupyterutils
extra:
  recipe-maintainers:
    - danielfrg
