travis:
  secure:
    BINSTAR_TOKEN: LxWE6sQpby+pdYPngDSXUuM46N9aMHKJrh/jbJcIL2Twm2G7LPv8HPga1+v9e1sjQfAR+TGspDpi/FtXCzS3N6hipr4yjRMebRTCTdDhroyThAR+KZEs9swO0OSSn9Rp3nU8dfP2CLLBEbmitkkqXSHo6Ab5NH803UCYfsyWHoQT0BAlVIlT6bI9uUN3nhr5c2uXuK0sqW3fYgmDVYiJoa5NCJFncxtW7bOdnIH4P9lrx2BlclKK6X+xD+n1iV9m9CWtbxdRrhUTGKJ7qkXz752sPn5C/yaTk8jYgHsniRzqkj8uaAoO23cfTStOLtm0S23d8kML3zJa8jkm57iYOYLDOkCSTNB5hpyCLwbCYcSUV/df+5hkEZvJxIxeHIuyDL6B5USg4z/YyymsyEEVLBfxpKqajbQvKVarWhzs1+24rV5etkGK8EZiLNVJ5rIlCUWWSGX+qV2uHYvyCWJcxA+qKENsIZnVH4fUx2+KiEO00Hp1Uy3/aIlv8R3MY7M2bhpt7MjRMyLg9jU8v1+qgN1EcW80NAgx1b9AoVlakM90o7n2Iw3qkQO5Y1Rs24gi0er139/HLs26fdo9s9YLfV5sL3f+NIuyGv3vgW8lsDrod/IfoGW54+AiOF+pDUVwdxkTSKPlzNoG/C7AdpE/iil95ARFMXhCjbcteG4Nrws=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
