travis:
  secure:
    BINSTAR_TOKEN: XcQIhyHREULDSQZ3yU1bukhT2TuqfT5cIzddkmCasd7bLdcvDdTsEB7CqEO+qDUNppDr9nH7djk8GH3CTBV8/yRWPK9az2swPlwvi9mEFy6UbrjJ7aRDBUr7WaWDwvsVa2yXlAaw3Fn3883kCpdo/Q1pS1aDHiG14wJZ0fUCCVVhlT+RtUK0JIM2zH+V1kOQNbU+YPB26Df7t30DAtU3m/AuROHr3jfZJIPFsq/4w+Bbgs16mAh/cxFDuKaBJ9HXnB78kjdK++yZxehBYahGamVT1jflRlHtY3LdeomwzsAU77SUmIaQrOtILGdbwQVLCJjLHo7yTIAwwNdrQoYQIWVYv4lFvGTsvX3GRBJjjfmzJWd1h/7L0dYsrdg0s1hGTSGw3eFgCnXaK04TjKkjVZy5WIOs3/PflTSCwhW2t8TXajYMPcEoFR03yxIWrGX3XBdmUjd+S02IZZPe3aqvyj2l6csewj8Q/EFT8/B+QIOIPe4wXakRvlMPojukgHwQQbgm7Urm835HNIMSwIP88Vy0ev5D8f9A3XEl8v4ejEXyFqIJmJsDBuIcyiKsuZaUMWElkrtttZ6kKexX/uX8T6no7sCQySMaQoOUPxk/5z7aw082ZzBOhYfFeulcZOklxju8qtpifQ29+QVYKi+beH/s9Eh/pNx4Y/6fU7Kglag=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
